/*
 * 
 * Custom Control to add textbox with placeholder text
 * Raw code here for reference
 * in current project, we're using the binary of this
 * to make changes to this control, you would have to add this code
 * to a separate custom control project, remove the autogenerated control'
 * that c#  loads. Simply add a new item "class" and paste this code in that class file.
 * Once this is done, clean the project and build. you should now be able to get
 * the binary of the updated customcontrol
 * 
 */
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace CustomControls
{
    public class SearchTextBox : PlaceholderTextBox
    {
        private const int EM_SETMARGINS = 0xd3;

        [System.Runtime.InteropServices.DllImport("user32.dll")]
        private static extern IntPtr SendMessage(IntPtr hWnd, int msg, IntPtr wp, IntPtr lp);

        private PictureBox searchPictureBox;

        private Button cancelSearchButton;

        public SearchTextBox()
        {
            Initialize();
        }
        private void Initialize() {
            cancelSearchButton = new Button();
            cancelSearchButton.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            cancelSearchButton.Size = new Size(16, 16);
            cancelSearchButton.TabIndex = 0;
            cancelSearchButton.TabStop = false;
            cancelSearchButton.FlatStyle = FlatStyle.Flat;
            cancelSearchButton.FlatAppearance.BorderSize = 0;
            cancelSearchButton.Text = "";
            cancelSearchButton.Cursor = Cursors.Arrow;

            Controls.Add(cancelSearchButton);

            cancelSearchButton.Click += delegate
            {
                Text = "";
                Focus();
            };

            searchPictureBox = new PictureBox();
            searchPictureBox.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            searchPictureBox.Size = new Size(16, 16);
            searchPictureBox.TabIndex = 0;
            searchPictureBox.TabStop = false;
            Controls.Add(searchPictureBox);

            // Send EM_SETMARGINS to prevent text from disappearing underneath the button
            SendMessage(Handle, EM_SETMARGINS, (IntPtr)2, (IntPtr)(16 << 16));

            UpdateControlsVisibility();
        }

        protected override void OnTextChanged(EventArgs e)
        {
            base.OnTextChanged(e);
            UpdateControlsVisibility();
        }

        private void UpdateControlsVisibility()
        {
            if (string.IsNullOrEmpty(Text))
            {
                cancelSearchButton.Visible = false;
                searchPictureBox.Visible = true;
            }
            else
            {
                cancelSearchButton.Visible = true;
                searchPictureBox.Visible = false;
            }
        }

        [Browsable(true)]
        public Image SearchImage
        {
            set
            {
                searchPictureBox.Image = value;
                searchPictureBox.Left = Width - searchPictureBox.Size.Width - 4;
                searchPictureBox.Top = Height - searchPictureBox.Size.Height - 4;
            }

            get { return searchPictureBox.Image; }
        }

        [Browsable(true)]
        public Image CancelSearchImage
        {
            set
            {
                cancelSearchButton.Image = value;
                cancelSearchButton.Left = Width - searchPictureBox.Size.Width - 4;
                cancelSearchButton.Top = Height - searchPictureBox.Size.Height - 4;
            }

            get { return cancelSearchButton.Image; }
        }
    }
}
